# ++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration           +
# project    nord                                    +
# repository https://github.com/arcticicestudio/nord +
# author     Arctic Ice Studio                       +
# email      development@arcticicestudio.com         +
# copyright  Copyright (C) 2017                      +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI
#   https://docs.travis-ci.com
language: node_js
dist: trusty
sudo: false
node_js:
  - "4"
  - "6"
  - "7"
os:
  - linux
  - osx
before_install:
  - rm -rf ./node_modules
before_script:
  - npm install -g gulp-cli
  - npm install gulp
  - npm install
script:
  - gulp --harmony clean
  - gulp --harmony lint
  - gulp --harmony compile-babel-js
  - npm run test
  - gulp --harmony compile-css-template
  - gulp --harmony sassdoc
  - gulp --harmony jsdoc
